AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Milvus and vector search Lambdas.

Parameters:
  MilvusHost:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/host
  MilvusPort:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/port
  MilvusCollection:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/collection

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.13
    Timeout: 60
    MemorySize: 512

Resources:
  MilvusInsertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-insert-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  MilvusDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-delete-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  MilvusUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-update-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  MilvusCreateCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-create-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  MilvusDropCollectionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-drop-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  VectorSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./vector-search-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  HybridSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./hybrid-search-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

Outputs:
  MilvusInsertFunctionArn:
    Description: ARN of the Milvus insert Lambda
    Value: !GetAtt MilvusInsertFunction.Arn
  MilvusDeleteFunctionArn:
    Description: ARN of the Milvus delete Lambda
    Value: !GetAtt MilvusDeleteFunction.Arn
  MilvusUpdateFunctionArn:
    Description: ARN of the Milvus update Lambda
    Value: !GetAtt MilvusUpdateFunction.Arn
  MilvusCreateCollectionFunctionArn:
    Description: ARN of the Milvus create collection Lambda
    Value: !GetAtt MilvusCreateCollectionFunction.Arn
  MilvusDropCollectionFunctionArn:
    Description: ARN of the Milvus drop collection Lambda
    Value: !GetAtt MilvusDropCollectionFunction.Arn
  VectorSearchFunctionArn:
    Description: ARN of the vector search Lambda
    Value: !GetAtt VectorSearchFunction.Arn
  HybridSearchFunctionArn:
    Description: ARN of the hybrid search Lambda
    Value: !GetAtt HybridSearchFunction.Arn
