AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Parent SAM template that includes individual service stacks.

Resources:
  IDPService:
    Type: AWS::Serverless::Application
    Properties:
      Location: services/idp/template.yaml

  SummarizationService:
    Type: AWS::Serverless::Application
    Properties:
      Location: services/summarization/template.yaml
