AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambdas for RAG ingestion.

Parameters:
  MilvusHost:
    Type: String
    Default: localhost
  MilvusPort:
    Type: Number
    Default: 19530
  MilvusCollection:
    Type: String
    Default: docs

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.13
    Timeout: 60
    MemorySize: 512

Resources:
  TextChunkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./text-chunk-lambda/

  EmbedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./embed-lambda/

  MilvusInsertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-insert-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection
