AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambdas for RAG ingestion.

Parameters:
  MilvusHost:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/host
  MilvusPort:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/port
  MilvusCollection:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/collection

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.13
    Timeout: 60
    MemorySize: 512

Resources:
  TextChunkFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./text-chunk-lambda/

  EmbedFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./embed-lambda/

  MilvusInsertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./milvus-insert-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

Outputs:
  TextChunkFunctionArn:
    Description: ARN of the text chunk Lambda
    Value: !GetAtt TextChunkFunction.Arn
  EmbedFunctionArn:
    Description: ARN of the embed Lambda
    Value: !GetAtt EmbedFunction.Arn
  MilvusInsertFunctionArn:
    Description: ARN of the Milvus insert Lambda
    Value: !GetAtt MilvusInsertFunction.Arn
