AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple router Lambda to direct prompts to Bedrock or Ollama.

Parameters:
  BedrockOpenAIEndpoint:
    Type: String
    Default: ''
  BedrockApiKey:
    Type: String
    Default: ''
  OllamaEndpoint:
    Type: String
    Default: ''
  OllamaDefaultModel:
    Type: String
    Default: ''
  PromptComplexityThreshold:
    Type: String
    Default: '20'

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.13
    Timeout: 60
    MemorySize: 512

Resources:
  RouterLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./router-lambda/
      Environment:
        Variables:
          BEDROCK_OPENAI_ENDPOINT: !Ref BedrockOpenAIEndpoint
          BEDROCK_API_KEY: !Ref BedrockApiKey
          OLLAMA_ENDPOINT: !Ref OllamaEndpoint
          OLLAMA_DEFAULT_MODEL: !Ref OllamaDefaultModel
          PROMPT_COMPLEXITY_THRESHOLD: !Ref PromptComplexityThreshold
      Events:
        Api:
          Type: Api
          Properties:
            Path: /route-llm
            Method: post

Outputs:
  RouterLambdaArn:
    Description: ARN of the router lambda
    Value: !GetAtt RouterLambda.Arn
