AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambdas for RAG retrieval.

Parameters:
  MilvusHost:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/host
  MilvusPort:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/port
  MilvusCollection:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /rag/milvus/collection
  TextChunkFunctionArn:
    Type: String
  EmbedFunctionArn:
    Type: String
  MilvusInsertFunctionArn:
    Type: String
  ClassifierFunctionArn:
    Type: String
  OfficeExtractorFunctionArn:
    Type: String
  PdfSplitFunctionArn:
    Type: String
  PdfPageClassifierFunctionArn:
    Type: String
  PdfTextExtractorFunctionArn:
    Type: String
  PdfOcrExtractorFunctionArn:
    Type: String
  CombineFunctionArn:
    Type: String
  OutputFunctionArn:
    Type: String
  SummaryEndpoint:
    Type: String
    Default: ''
  ContentEndpoint:
    Type: String
    Default: ''
  EntitiesEndpoint:
    Type: String
    Default: ''

Globals:
  Function:
    Handler: app.lambda_handler
    Runtime: python3.13
    Timeout: 60
    MemorySize: 512

Resources:
  VectorSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./vector-search-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  HybridSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./hybrid-search-lambda/
      Environment:
        Variables:
          MILVUS_HOST: !Ref MilvusHost
          MILVUS_PORT: !Ref MilvusPort
          MILVUS_COLLECTION: !Ref MilvusCollection

  SummarizeWithContextFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./summarize-with-context-lambda/
      Environment:
        Variables:
          VECTOR_SEARCH_FUNCTION: !Ref VectorSearchFunction
          SUMMARY_ENDPOINT: !Ref SummaryEndpoint
      Events:
        Api:
          Type: Api
          Properties:
            Path: /summarize
            Method: post

  ContentExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./extract-content-lambda/
      Environment:
        Variables:
          VECTOR_SEARCH_FUNCTION: !Ref VectorSearchFunction
          CONTENT_ENDPOINT: !Ref ContentEndpoint
      Events:
        Api:
          Type: Api
          Properties:
            Path: /extract-content
            Method: post

  EntityExtractionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./extract-entities-lambda/
      Environment:
        Variables:
          VECTOR_SEARCH_FUNCTION: !Ref VectorSearchFunction
          ENTITIES_ENDPOINT: !Ref EntitiesEndpoint
      Events:
        Api:
          Type: Api
          Properties:
            Path: /extract-entities
            Method: post

  RagWorkflowStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        Comment: Process document with IDP and ingest into Milvus
        StartAt: ClassifyDocument
        States:
          ClassifyDocument:
            Type: Task
            Resource: !Ref ClassifierFunctionArn
            Next: OfficeExtract
          OfficeExtract:
            Type: Task
            Resource: !Ref OfficeExtractorFunctionArn
            Next: PdfSplit
          PdfSplit:
            Type: Task
            Resource: !Ref PdfSplitFunctionArn
            Next: PdfPageClassify
          PdfPageClassify:
            Type: Task
            Resource: !Ref PdfPageClassifierFunctionArn
            Next: PdfTextExtract
          PdfTextExtract:
            Type: Task
            Resource: !Ref PdfTextExtractorFunctionArn
            Next: PdfOcrExtract
          PdfOcrExtract:
            Type: Task
            Resource: !Ref PdfOcrExtractorFunctionArn
            Next: CombineResults
          CombineResults:
            Type: Task
            Resource: !Ref CombineFunctionArn
            Next: OutputDocument
          OutputDocument:
            Type: Task
            Resource: !Ref OutputFunctionArn
            ResultPath: $.document
            Next: ChunkText
          ChunkText:
            Type: Task
            Resource: !Ref TextChunkFunctionArn
            InputPath: $.document
            ResultPath: $.chunk
            Next: EmbedText
          EmbedText:
            Type: Task
            Resource: !Ref EmbedFunctionArn
            InputPath: $.chunk
            ResultPath: $.embedding
            Next: MilvusInsert
          MilvusInsert:
            Type: Task
            Resource: !Ref MilvusInsertFunctionArn
            InputPath: $.embedding
            ResultPath: $.insert
            End: true
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref ClassifierFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref OfficeExtractorFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref PdfSplitFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref PdfPageClassifierFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref PdfTextExtractorFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref PdfOcrExtractorFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref CombineFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref OutputFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref TextChunkFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref EmbedFunctionArn
        - LambdaInvokePolicy:
            FunctionName: !Ref MilvusInsertFunctionArn

Outputs:
  VectorSearchFunctionArn:
    Description: ARN of the vector search Lambda
    Value: !GetAtt VectorSearchFunction.Arn
